name: dev_dagger
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argcomplete=1.12.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - certifi=2021.10.8
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cudatoolkit=11.3.1
  - cycler=0.10.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - future=0.18.2
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gpytorch=1.5.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gym=0.21.0
  - h5py=3.6.0
  - hdf5=1.10.6
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.4.0
  - ipdb=0.13.9
  - ipykernel=6.6.0
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.3
  - jpeg=9d
  - jsonschema=2.6.0
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbconvert=5.6.1
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.7.3
  - notebook=5.7.11
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.0.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.22
  - ptyprocess=0.7.0
  - pyglet=1.5.16
  - pygments=2.10.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2021.4.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.11
  - torchvision=0.11.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.2
  - x264=1!157.20191217
  - xz=5.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
